FROM alpine:latest
RUN apk update && apk add curl git  wget
# docker.io/aeleniumfor/dev_alpine

# ctr i pull docker.io/aeleniumfor/dev_alpine
# ctr c create docker.io/aeleniumfor/dev_alpine:latest alpine
# ctr t start -d alpine
# ctr t exec -t --exec-id 5000 alpine ash