- hosts: master
  tasks:
    - name: yum update
      yum: name=* state=latest

    - name: yum install pakeages
      yum:
        name: "{{ packages }}"
      vars:
        packages:
          - git
          - wget
          - curl

    - name: download containerd files
      get_url: url="https://github.com/containerd/containerd/releases/download/v1.2.4/containerd-1.2.4.linux-amd64.tar.gz" dest=./
    
    - name: download runC files
      get_url: url="https://github.com/opencontainers/runc/releases/download/v1.0.0-rc5/runc.amd64" dest=./
    
    - name: move runc.amd64  /usr/bin/runc
      shell: >
        chmod +x runc.amd64;
        mv ./runc.amd64 /usr/bin/runc;

    - name: containerd files unarchive
      command: tar zxvf ./containerd-1.2.4.linux-amd64.tar.gz -C /usr/local/

    - name: move containerd.service in /etc/systemd/system/
      copy: >
        src=./containerd.service
        dest=/etc/systemd/system/containerd.service
        owner=root
        group=root
        mode=0644
    - name: systemd
      systemd:
        name: containerd.service
        state: restarted
        daemon_reload: yes
        enabled: yes

    - name: cni-tool install
      command: tar zxvf ./containerd-1.2.4.linux-amd64.tar.gz -C /usr/local/