- hosts: master
  tasks:
    - name: yum update
      yum: name=* state=latest

    - name: yum install pakeages
      yum:
        name: "{{ packages }}"
      vars:
        packages:
          - git
          - wget
          - curl
          - bridge-utils
          - nginx
          
    - name: nginx firewall
      firewalld: service=http permanent=true state=enabled immediate=true
    
    - name: systemd
      systemd:
        name: nginx.service
        state: restarted
        daemon_reload: yes
        enabled: yes
